services:
  - type: web
    name: demo-day-voting
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: ADMIN_PIN
        value: "2026"
